######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 8 19:59:30 2008
######################################################################

TEMPLATE = app
TARGET = fDetect
DEPENDPATH += .
LIBS += -lopencv_videoio -lopencv_objdetect -lopencv_imgproc -lopencv_highgui -lopencv_core

QT += core

SOURCES += main.cpp \
    Face.cpp

HEADERS += \
    Face.h
